-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 19:58:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank_security
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank_security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank_security` DEFAULT CHARACTER SET latin1 ;
USE `bank_security` ;

-- -----------------------------------------------------
-- Table `bank_security`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_security`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) CHARACTER SET 'latin1' NOT NULL,
  `hash` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `username` VARCHAR(120) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `previleges` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_security`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_security`.`accounts` (
  `id` INT(155) NOT NULL AUTO_INCREMENT,
  `status` INT(11) NOT NULL,
  `client_type` INT(11) NULL DEFAULT NULL,
  `balance` VARCHAR(45) NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Client_ID` (`id` ASC),
  INDEX `fk_accounts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `bank_security`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 223
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_security`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_security`.`operations` (
  `id` INT(11) NOT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `value` VARCHAR(50) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `acc_id1` INT(11) NULL DEFAULT NULL,
  `acc_id2` INT(11) NULL DEFAULT NULL,
  `accounts_id` INT(155) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operations_accounts1_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_operations_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `bank_security`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_security`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_security`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `gender` TEXT NULL,
  `address` TEXT NULL,
  `phone` INT(9) NULL,
  `country` TEXT NULL,
  `birthday` VARCHAR(100) NULL,
  `city` TEXT NULL,
  `zipcode` TEXT NULL,
  `district` TEXT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_profile_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `bank_security`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
